version: "3.8"
services:
  database:
    image: postgres:10
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  app:
    build:
      context: .
    env_file:
    - ./dev.env
    command: ["python", "/mnt/runserver.py"]
    ports:
    - "5000:5000"
    volumes:
    - .:/mnt
    depends_on:
    - database
